### ISSUE TITLE
Preserve tildes (~)

### ISSUE THREAD

**Issue by samselikoff** [Alonski/prettier-for-handlebars-vscode#11]
The ~ character is used to remove whitespace in HBS, I believe this extensions is removing it:

```hbs
  <pre>
    {{~this.json}}
  </pre>
```

becomes

```hbs
  <pre>
    {{this.json}}
  </pre>
```

**Comment by Alonski** [comment]
@samselikoff Is this still an issue with latest Prettier?
If not can you please comment here?
https://github.com/jgwhite/prettier/issues/1#issuecomment-602504650

**Comment by samselikoff** [comment]
seems like it's fixed!
