### ISSUE TITLE
formatter self-closes void elements

### ISSUE THREAD

**Issue by brokenalarms** [Alonski/prettier-for-handlebars-vscode#14]
eg `<input />`. This is disallowed by our styleguide (and generally discouraged now, see eg https://hackernoon.com/to-close-or-not-to-close-4365d24853ff)

**Comment by Alonski** [comment]
This is a Prettier default from what I understand :)
Not much to do about it unless Prettier is updated.
You could comment here about this issue:
https://github.com/jgwhite/prettier/issues/1

**Comment by brokenalarms** [comment]
Thanks for your answer. Took me a while to unpack all the differences between prettier, ember template lint, and the extensions. This part isn't your problem in any extent.
