### ISSUE TITLE
Array access in templates

### ISSUE THREAD

**Issue by betocantu93** [Alonski/prettier-for-handlebars-vscode#6]
Hello, great extension!
```hbs
{{enum-t model attribute changes.[1]}} 
{{!-- gets formatted into --}}
{{enum-t model attribute changes.1}}
```
Which then causes a template compiler error... Any hints? 

Also, I'm trying to run prettier in the whole directory with `prettier --write app/**/*.hbs` and I would like to apply all of this vscode extension prettier options, what's are them? I'm not really used to config prettier, but... I copied what you mainly had over src/extension.ts `{ parser: glimmer, printWidth: 120 }` not sure what else I need because I noticed that when I manually format a template with this extension i.e CMD + P + format..., my unnecessary new lines gets removed (which I like), but this is not happening when running the prettier command which reads from my .prettierrc

```js
module.exports = {
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  quoteProps: 'as-needed',
  trailingComma: 'none',
  bracketSpacing: true,
  arrowParens: 'avoid',
  proseWrap: 'preserve',
  printWidth: 100,
  overrides: [
    {
      files: '*.hbs',
      options: {
        parser: 'glimmer',
        singleQuote: false,
        printWidth: 120
      }
    }
  ]
};


```

**Comment by Alonski** [comment]
Hey @betocantu93 Sorry for the late response.
You have to pin your Prettier version to the same one used by this extension, at this time 1.18.2.

Prettier changes frequently between releases.
Also this extension doesn't handle `singleQuote` false :)

**Comment by Alonski** [comment]
Also @betocantu93 regarding `{{enum-t model attribute changes.[1]}}`
This isn't "valid" syntax. It works but shouldn't be relied upon. I recommend using the `get` helper or the `object-at` helper from Ember Composable Helpers.

**Comment by betocantu93** [comment]
Thanks @Alonski will reopen if something shows up
