### ISSUE TITLE
Preserve blank lines

### ISSUE THREAD

**Issue by nightire** [Alonski/prettier-for-handlebars-vscode#9]
It's very helpful for readability and maintainability if intentional blank lines could be preserved. This is the only thing left that I loved so much in [handlebars-formatter](https://github.com/mfeckie/handlebars-formatter), it handled this case pretty well: only one blank line will be preserved and excess will be removed.

Can we support this feature as well? Thanks!

**Comment by nightire** [comment]
@Alonski I'm bringing this issue up again because of other people ask the same:
https://github.com/jgwhite/prettier/issues/1#issuecomment-607273019

Can we have this support? I'm willing to migrate from [handlebars-formatter](https://github.com/mfeckie/handlebars-formatter) to this one, this is the only road-block to me.

**Comment by Alonski** [comment]
@nightire This extension is 99% the same as `handlebars-formatter`. I pretty much just copied the code with a few different defaults. 
Right now this extension uses Prettier 1.18.2
`handlebars-formatter` uses Prettier 1.19.0

There is currently inconsistent behavior in Prettier versions higher than 1.18.2.
I wrote about this here: https://github.com/jgwhite/prettier/issues/1#issuecomment-602504650

This is what is currently preventing me from bumping Prettier version to latest.

Other than this I don't think there is much I can do right now :)

**Comment by nightire** [comment]
@Alonski Okay, I understand it better now. Thanks for your patience.

**Comment by Alonski** [comment]
@nightire Are you saying that if you use Prettier v1.19.0 from the command line via the Prettier CLI it preserves whitespace differently than `handlebars-formatter`?

**Comment by nightire** [comment]
> @nightire Are you saying that if you use Prettier v1.19.0 from the command line via the Prettier CLI it preserves whitespace differently than `handlebars-formatter`?

No. It's my fault because I don't know `handlebars-formatter` has a bundled version of Prettier. I have thought it uses the local version copy, my bad, sorry for my misleading.
